version: "3.8"

volumes:
  node_modules:

services:

    mariadb:
        image: "mariadb"
        container_name: "mariadb"
        volumes:
          - ./mariadb/:/docker-entrypoint-initdb.d
        environment:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
        restart: 
            "always"

    express:
        image: "express"
        container_name: "express"
        build: "./server"
        working_dir: "/express/app"
        volumes:
          - "./server/app/:/express/app"
          - "node_modules:/express/app/node_modules"
        ports:
          - "1337:1337"
        command: npm run dev
        restart:
            "on-failure"
